server.port=8088

spring.mongodb.uri=mongodb://polychain-user:polychain-password@localhost:27019/polychain-auth?authSource=admin
mongodb.database=polychain-auth
mongodb.ssl.enabled=false
mongodb.ssl.cert=global-bundle.pem
internal.secret=${INTERNAL_SECRET}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}
